### ISSUE TITLE
File to import not found or unreadable: n-ui/env

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/next-messaging#36]
When trying to build `n-ui`, it errors with `File to import not found or unreadable: n-ui/env
Parent style sheet: /Users/adambraimbridge/Sites/n-ui/bower_components/n-notification/main.scss':
![image](https://cloud.githubusercontent.com/assets/224547/17892938/9567a8d2-693b-11e6-8a03-e7ed3b787662.png)

And trying to build it in `n-notification` errors with `webpack-stream - No files given; aborting compilation`:
![image](https://cloud.githubusercontent.com/assets/224547/17892906/70279a82-693b-11e6-9d38-c081ff4316b2.png)

**Comment by bjfletcher** [comment]
Um....

**Comment by wheresrhys** [comment]
Ah, I changed the build process to make it quicker, but only added the change for when in CI. 

I'll add it to dev too
