### ISSUE TITLE
Move myft-ui__icon class definition to n-myft-ui?

### ISSUE THREAD

**Issue by dan-searle** [Financial-Times/next-messaging#48]
The `.myft-ui__icon` class is defined in here but is used in the article save notification - the code for which is in https://github.com/Financial-Times/n-myft-ui

That class definition should be moved out of here and into n-myft-ui.

https://github.com/Financial-Times/n-notification/search?q=.myft-ui__icon&unscoped_q=.myft-ui__icon

**Comment by chee** [comment]
this has been moved to `done` in 2018
